raise_task:
  description: >
    Try to get a raise.
  expected_output: >
    None
  agent: mcdonalds_worker


no_raise_task:
  description: >
    Try as hard as you can to not give the raise.
  expected_output: >
    None
  agent: mcdonalds_boss